---
title: Agência Gift - Comunidade de desenvolvedores
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
description: 'Compartilhe conteúdos úteis na área de tecnologia.  Informe sugestões
  de projetos. Monte seu time de hackathon. Compartilhe vagas.

'
baseurl: ''
url: http://agenciagft.github.io
markdown: kramdown
exclude:
- gulpfile.js
- README.md
- desktop.ini
